### ISSUE TITLE
Количество взятых вопросов различается в статистике и в профиле

### ISSUE THREAD

**Issue by DasIgnis** [nktfmnko/cgkTraining#24]
Сценарий - установила приложение, сыграла пару тренировок не на время, пару тренировок на время, снова пару тренировок не на время. Количество взятых вопросов стало отличаться в статистике на вкладке рейтинга и в статистике профиля. Они либо не должны отличаться, либо надо эти два счетчика назвать по-разному, если они и должны содержать два разных значения

**Comment by nktfmnko** [comment]
Количество взятых вопросов в статистике на вкладке рейтинга и в статистике профиля - это одно и тоже значение, возможно, не успели обновиться данные. В последней версии добавлено принудительное обновление главного экрана по свайпу вниз, чтобы подтянуть актуальное значение взятых вопросов.
