### ISSUE TITLE
Избавиться от механики "запомнить меня"

### ISSUE THREAD

**Issue by MihaxXx** [nktfmnko/cgkTraining#33]
Механика "запомнить меня" не имеет смысла в мобильном приложении, так как смартфон общего пользования - та ещё редкость

**Comment by nktfmnko** [comment]
[Удалена кнопка "запомнить меня"](https://github.com/nktfmnko/cgkTraining/commit/88a534f7e583490652c686f6ed3511182dac7a4e)
